### ISSUE TITLE
Fatal Crash 1.6.1 - MC Server 1.15.2

### ISSUE THREAD

**Issue by PanoptesDreams** [ExtraCrafTX/ExtraDoors#2]
[18:07:16] [main/FATAL]: Mixin apply failed extradoors.mixins.json:EntityAccessor -> net.minecraft.class_1297: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching teleportRequested:Z in net/minecraft/class_1297 for extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V [INJECT Applicator Phase -> extradoors.mixins.json:EntityAccessor -> Apply Accessors ->  -> Locate -> extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching teleportRequested:Z in net/minecraft/class_1297 for extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V [INJECT Applicator Phase -> extradoors.mixins.json:EntityAccessor -> Apply Accessors ->  -> Locate -> extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V]
        at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1307) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1051) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) [?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) [?:1.8.0_241]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) [fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) [?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) [?:1.8.0_241]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) [fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_241]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_241]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) [?:1.8.0_241]
        at java.lang.Class.privateGetMethodRecursive(Unknown Source) [?:1.8.0_241]
        at java.lang.Class.getMethod0(Unknown Source) [?:1.8.0_241]
        at java.lang.Class.getMethod(Unknown Source) [?:1.8.0_241]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [extradoors.mixins.json:EntityAccessor] from phase [DEFAULT] in config [extradoors.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching teleportRequested:Z in net/minecraft/class_1297 for extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V [INJECT Applicator Phase -> extradoors.mixins.json:EntityAccessor -> Apply Accessors ->  -> Locate -> extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V]
        at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518)
        at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501)
        at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1307)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1051)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 31 more
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        ... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:191)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        ... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [extradoors.mixins.json:EntityAccessor] from phase [DEFAULT] in config [extradoors.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
        ... 31 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching teleportRequested:Z in net/minecraft/class_1297 for extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V [INJECT Applicator Phase -> extradoors.mixins.json:EntityAccessor -> Apply Accessors ->  -> Locate -> extradoors.mixins.json:EntityAccessor->@Accessor[FIELD_SETTER]::setTeleportRequested(Z)V]
        at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518)
        at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501)
        at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475)
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1307)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1051)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
        ... 31 more

**Comment by ExtraCrafTX** [comment]
Thanks for this report, there is a really annoying issue with refmaps in Loom and it trips me up every time, will be fixed in the next release (1.7.0) which should come in the next few minutes
